version: '3.9'

services:
  #light service: php
  app-lambda:
    image: app-lambda
    container_name: app-lambda
    build:
      context: .
      dockerfile: ./docker/lambda.Dockerfile
    working_dir: /var/task
    env_file:
      - ./.env
    ports:
      - target: 8080
        published: 9001
        protocol: tcp
        mode: host
    entrypoint: "/aws-lambda/aws-lambda-rie"
    volumes:
      - ~/.aws-lambda-rie:/aws-lambda
      - ./:/var/task
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"
